Reduce excessive calls to `/totals`
rilldata/rill pull request #2563
Opened 2023-06-06 05:02 UTC by ericpgreen2

## Checklist
- [x] Manual verification
- [ ] Unit test coverage
- [ ] E2E test coverage
- [x] Needs manual QA?

## Summary
#### Issue addressed: 
[Notion page](https://www.notion.so/rilldata/Only-run-queries-once-dashboard-state-is-initialized-451de063dba34117a4cccfdc189e17ae?d=ac03ba48ef4d45ac865bc46068a7164e)

#### Details:
This PR applies TanStack Query's `enabled` flag to each `/totals` request. We ensure that we only submit a request once the dashboard's time range and filters have been set.

Most significantly, if we issue the request without a time range, the backend will assume the query applies to the all time range. Querying the all time range locks up a Druid cluster.

## Steps to Verify
1. Open a dashboard
2. Open your browser devtools
3. Go to the Network tab
4. Filter for `/totals`
5. Refresh the dashboard page and observe 1 request to `/totals`. Previously, there were 4 requests to `/totals`.

2023-06-07 18:06 UTC, skokenes requested changes
I have some minor comments here. I was going to approve regardless of those, but now I am seeing 2 "totals" calls in my devTools, not 1. So I am wondering if its related to these?
<img width="1216" alt="image" src="https://github.com/rilldata/rill-developer/assets/5554373/f9b38a5d-8d7f-488b-a88f-ad41637bc8c5">

2023-06-08 05:58 UTC, ericpgreen2 commented on web-common/src/features/dashboards/big-number/MeasuresContainer.svelte
> +        : undefined,
You're totally right. I thought I tested that chaining before, and it errored, but I must’ve been missing a question mark.

2023-06-08 06:05 UTC, ericpgreen2 commented on web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
> +        enabled: hasTimeSeries ? !!metricsExplorer.selectedTimeRange : true,
Because there are no filters in this request. The result is used as the denominator in a % of total calculation.

2023-06-08 06:46 UTC, ericpgreen2 commented
Dang, you're right, I'm seeing a redundant call as well. It seems to happen about 25-50% of the time, and only for custom time ranges. Where you see 3 calls, I believe you have comparisons enabled, which should trigger 2 calls to totals, so you're seeing n+1 requests.

Based on the call stack of the redundant request, it looks to be deriving from the `TimeControls.svelte` file. Because of the complexity in that file, it's a bigger project to track this down.

Given it's complex, somewhat of an edge case, and this PR accomplishes its main goal of reducing requests without a time range, I propose we merge this as is. Does that work?

2023-06-09 15:49 UTC, skokenes approved these changes

2023-06-09 15:49 UTC, skokenes commented
Yes I agree, lets not let perfect be the enemy of good. Lets merge it

2023-06-09 15:49 UTC, merged