2649 cli implement whoami command
rilldata/rill pull request #2674
Opened 2023-06-22 06:13 UTC by rakeshsharma14317

2023-06-26 18:26 UTC, begelundmuller requested changes

2023-06-26 18:26 UTC, begelundmuller commented on cli/cmd/whoami/whoami.go
> +		RunE: func(cmd *cobra.Command, args []string) error {
Add `PersistentPreRunE: cmdutil.CheckAuth(cfg),`

2023-06-26 18:26 UTC, begelundmuller commented on cli/cmd/whoami/whoami.go
> +			fmt.Printf("  You Logged in as : %s\n", res.User.Email)
Output:
```
Email: <email>
Name: <display name>
```

2023-07-03 10:38 UTC, nishantmonu51 approved these changes

2023-07-03 13:49 UTC, begelundmuller approved these changes

2023-07-03 13:49 UTC, merged