Additional queries validation
rilldata/rill pull request #2712
Opened 2023-06-28 18:02 UTC by egor-ryashin

2023-06-29 19:26 UTC, begelundmuller requested changes

2023-06-29 19:26 UTC, begelundmuller commented on proto/rill/runtime/v1/queries.proto
> +  int32 pixels = 7 [(validate.rules).int32.gt = 0];
Doesn't the API support 0 for this?

2023-06-29 19:26 UTC, begelundmuller commented on runtime/server/queries_metrics.go
> +}
I think you can just use proto validations – only the `measures` slice defines what measures are returned, the inline measures I believe just inject extra definitions

2023-06-30 10:15 UTC, egor-ryashin commented on proto/rill/runtime/v1/queries.proto
> +  int32 pixels = 7 [(validate.rules).int32.gt = 0];
yes, good catch

2023-06-30 13:07 UTC, begelundmuller requested changes
1. Needs to re-generate the proto files for changes to take effect
2. Please do `make cli` and do an experience pass on `./rill start` with a simple project?Just to make sure the UI doesn’t depend on making funny queries

2023-07-03 13:47 UTC, begelundmuller approved these changes

2023-07-03 13:48 UTC, merged