2744 admin persist user preferences and dashboard state
rilldata/rill pull request #2765
Opened 2023-07-11 12:05 UTC by rakeshsharma14317

2023-07-12 11:15 UTC, begelundmuller commented on admin/server/bookmarks.go
> +	}
Return error if not a user

2023-07-12 11:15 UTC, begelundmuller commented on admin/server/bookmarks.go
> +
Check that the caller has read permission on the bookmark's project

2023-07-12 11:16 UTC, begelundmuller commented on admin/server/bookmarks.go
> +	}
Return error if not a user

2023-07-12 11:16 UTC, begelundmuller commented on admin/server/bookmarks.go
> +	bookmark, err := s.admin.DB.InsertBookmark(ctx, &database.InsertBookmarkOptions{
First check the caller has read permission on the project

2023-07-12 11:16 UTC, begelundmuller commented on admin/server/bookmarks.go
> +		UserID:        req.UserId,
Use `claims.OwnerID`

2023-07-12 11:16 UTC, begelundmuller commented on admin/server/bookmarks.go
> +	}
Return error if not a user

2023-07-12 11:17 UTC, begelundmuller commented on admin/server/bookmarks.go
> +	err := s.admin.DB.DeleteBookmark(ctx, req.BookmarkId)
First get the bookmark and check that the `OwnerID` matches the bookmark's user ID

2023-07-12 11:17 UTC, begelundmuller commented on admin/server/users.go
> +	}
Return error if not a user

2023-07-12 11:18 UTC, begelundmuller commented on admin/server/users.go
> +	observability.AddRequestAttributes(ctx, attribute.String("user_id", claims.OwnerID()))
Not needed, claims are logged separately

2023-07-12 11:19 UTC, begelundmuller commented on admin/server/users.go
> +	}
Use `time.LoadLocation` (and import `_ "time/tzdata"`) to validate that it's a valid time zone

2023-07-12 11:21 UTC, begelundmuller commented on proto/rill/admin/v1/api.proto
> +}
Can remove `user_id` – it should always return for the current user

2023-07-12 11:22 UTC, begelundmuller commented on proto/rill/admin/v1/api.proto
> +  string user_id = 2;
User ID is not needed (always assume current user)

2023-07-12 11:25 UTC, begelundmuller commented on proto/rill/admin/v1/api.proto
> +message DashboardBookmark {
For consistency, should just be `Bookmark` (since the APIs are all `CreateBookmark`, etc.)

2023-07-12 11:25 UTC, begelundmuller commented on proto/rill/admin/v1/api.proto
> +  optional string timezone = 1;
nit: should be `time_zone` (two words). This probably applies in other places as well (`TimeZone` instead of `Timezone)

2023-07-17 09:41 UTC, nishantmonu51 commented on admin/database/postgres/migrations/0010.sql
> +	project_id UUID NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
indentation

2023-07-18 14:35 UTC, begelundmuller requested changes

2023-07-18 14:35 UTC, begelundmuller commented on admin/server/bookmarks.go
> +	}
Remove the anon check, checking `!= auth.OwnerTypeUser` is sufficient

2023-07-18 14:35 UTC, begelundmuller commented on admin/server/bookmarks.go
> +	}
Same comment, can just be one check (see other functions that do such checks)

2023-07-18 14:35 UTC, begelundmuller commented on admin/server/bookmarks.go
> +	}
One check is sufficient

2023-07-18 14:35 UTC, begelundmuller commented on admin/server/bookmarks.go
> +	}
Same

2023-07-18 16:04 UTC, begelundmuller approved these changes

2023-07-18 16:04 UTC, merged