Export fixes
rilldata/rill pull request #3193
Opened 2023-10-07 05:47 UTC by pjain1

Fixes #3178 and #3177 

Since this changes the aliases to label instead of name in the sql query of toplist API, should we make similar change to other APIs as well ?

2023-10-09 12:11 UTC, begelundmuller requested changes

2023-10-09 12:11 UTC, begelundmuller commented on runtime/queries/metricsview.go
> +
Can we pass this as an explicit parameter or property instead? Context values are similar to reflection, best only to use them if truly necessary

2023-10-09 12:11 UTC, begelundmuller commented on runtime/queries/metricsview_comparison_toplist.go
> +		expr := fmt.Sprintf(`%s as %s`, m.Expression, safeName(q.measureNameToLabel[m.Name]))
Measure labels are not guaranteed to be unique. They can't be used inside the query for ordering/filtering/etc.

They should only be used at the export stage or in the query passed to `COPY TO` (where DuckDB will add numbers to disambiguate).

2023-10-09 12:11 UTC, begelundmuller commented on runtime/queries/metricsview_comparison_toplist.go
> +				safeName(q.measureNameToLabel[m.Name]+"__delta_rel"),
Do human-friendly formatting like `Label (prev)`, `Label (Δ)`, `Label (Δ%)`

2023-10-19 04:11 UTC, nishantmonu51 commented
@pjain1 : Do we still need these fixes ? Lets get the comments & conflicts resolved or close the PR if its not required anymore.

2023-10-22 13:07 UTC, begelundmuller commented
Closing since the limit issue was fixed in another PR, and the headers issue will be addressed in a separate PR

2023-10-22 13:07 UTC, closed without merging