Comparison API: refactoring
rilldata/rill pull request #3249
Opened 2023-10-17 10:37 UTC by egor-ryashin

2023-10-22 13:33 UTC, begelundmuller approved these changes
LGTM – before merging, let's have @ericpgreen2 take a look at the frontend changes

2023-10-22 21:51 UTC, ericpgreen2 approved these changes

2023-10-22 21:56 UTC, ericpgreen2 commented
However... I just noticed a panic when trying to export a dimension detail table's comparison data

2023-10-22 21:58 UTC, ericpgreen2 requested changes
What I see of the frontend changes looks good to me, but the app is crashing on me when trying to export a dimension detail table's comparison data

2023-10-24 15:14 UTC, ericpgreen2 approved these changes

2023-10-25 18:09 UTC, merged