Adityahegde/measure filters frontend
rilldata/rill pull request #3815
Opened 2024-01-10 07:30 UTC by AdityaHegde

## Checklist
- [x] Manual verification
- [x] Unit test coverage
- [x] E2E test coverage
- [x] Needs manual QA?

## Summary
#### Issue addressed: 

#### Details:

## Steps to Verify

2024-01-24 12:30 UTC, mindspank commented on web-common/src/features/dashboards/filters/measure-filters/MeasureFilterMenu.svelte
> +      value1: yup.number().required(),
NIT: Form error validation looks kinda ugly as it takes the property name

![image](https://github.com/rilldata/rill/assets/1181922/ff319f13-2e29-4c10-9604-b0c46241a696)

2024-01-24 19:19 UTC, briangregoryholmes requested changes
Looks like the right approach overall. There are a few nits, but a couple important functional issues that I'll describe here:

1. Start to add a measure filter, but fill out the value before selecting the dimension or threshold. The filter will not be added.
2. Add a measure filter. Select a different dimension option and close out of the menu. You'll see the measure does not update.
3. Add a measure filter. Change the Dimension to something else and then update the value. The visible measure pill does not update, but the dashboard does. If you close out of the menu and attempt to remove the pill, you'll see that the two filters appear to be "stacked" on top of each other.

2024-01-24 19:19 UTC, briangregoryholmes commented on web-common/src/components/forms/Select.svelte
>  <div class="flex flex-col gap-y-2">
The Figma includes some placeholder text for these Select components: https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=7116-382806&mode=design&t=8UeglpfHSPS7bIzz-0

2024-01-24 19:19 UTC, briangregoryholmes commented on web-common/src/features/dashboards/filters/measure-filters/MeasureFilterMenu.svelte
> +        detach
Should these have a more explicit `on:change` trigger like the Input component? There's a reactive statement on line 103 that tracks the `$form["operation"]` value, but not the `$form["dimension"]` value.

2024-01-25 09:39 UTC, AdityaHegde commented on web-common/src/features/dashboards/filters/measure-filters/MeasureFilter.svelte
> +<WithTogglableFloatingElement
Ya I am hoping we will do a refactor at once. Sadly this feature is a blocker for alerts so we can take the refactor up as a follow up.

2024-01-25 10:12 UTC, AdityaHegde commented
Good catch! Have fixed the issues. We really should move to shadcn's select components. The ones we have are lacklustre.

2024-01-26 17:38 UTC, briangregoryholmes approved these changes

2024-01-29 06:49 UTC, merged