fix spinner gradient
rilldata/rill pull request #3933
Opened 2024-01-29 21:43 UTC by bcolloran

fixes #3913 

default brand theme:
![firefox_OCp4dYBc7c](https://github.com/rilldata/rill/assets/2380975/f5c47c05-06e2-426f-bb6c-2414d522421c)

custom user theme from orange to green
![firefox_N3ldMBhFsY](https://github.com/rilldata/rill/assets/2380975/bc8f592e-dc02-45ee-abcb-d647aa38406d)

2024-01-29 22:02 UTC, bcolloran commented
fixes https://github.com/rilldata/rill/issues/3905 and https://github.com/rilldata/rill/issues/3913

2024-01-30 07:17 UTC, jkhwu requested changes
At the time of my review, it seems the spinner color is darker than intended in the design, which was secondary 500 - primary 500. I think they're both set to 700 in this branch. Here's a gif of what I'm seeing.
![Jan-29-2024 23-13-04](https://github.com/rilldata/rill/assets/30886488/0cc14a08-acc5-438e-80d4-914a603a7b0d)

2024-01-30 17:42 UTC, bcolloran commented
@jkhwu updated to 500/500. Sorry about that, when I was doing the fix I was looking at the theme regression bug #3913 and trying to match that previous state, and I didn't spot the callout for the new gradients in #3905

2024-01-30 19:07 UTC, jkhwu approved these changes

2024-01-30 19:12 UTC, ericpgreen2 approved these changes

2024-01-30 19:13 UTC, merged