MetricsView aggregation filters
rilldata/rill pull request #3975
Opened 2024-02-06 12:09 UTC by egor-ryashin

2024-02-06 14:19 UTC, egor-ryashin commented on proto/rill/runtime/v1/queries.proto
> +  Condition filter = 4;
That makes possible to create `FILTER (WHERE "column1)` if `ident` or `FILTER (WHERE ?)` if `val`. That makes it look ambiguous for a casual reader.

2024-02-06 16:35 UTC, begelundmuller commented on proto/rill/runtime/v1/queries.proto
> +  Condition filter = 4;
I believe the `Expression` to SQL converter handles those cases, i.e. it should escape identifiers and use `?` with query args for values.

2024-02-06 16:36 UTC, begelundmuller commented on proto/rill/runtime/v1/queries.proto
> +  Condition filter = 4;
(If not, we should fix that because it could also lead to issues with the `where` and `having` parameters in those cases)

2024-02-07 12:15 UTC, begelundmuller requested changes

2024-02-07 12:15 UTC, begelundmuller commented on runtime/queries/metricsview_aggregation.go
> +		condClause, condArgs, err := buildConditionExpression(mv, filter.GetCond(), nil, dialect)
Should use `buildExpression` on `filter` here since `filter` is not guaranteed to be a `Cond` any more

2024-02-07 13:15 UTC, merged