Remove Portal component and replace usage with action
rilldata/rill pull request #4216
Opened 2024-02-29 21:30 UTC by briangregoryholmes

This PR removes usage of the Portal component and replaces it with a more stable and safe action.

Previously, the Portal component would remove/append the portal to the DOM every time it was needed and the creation of one portal did not mean that it would be re-used for another element. Its implementation as a component also obfuscated exactly what was happening in ways that caused it to be used incorrectly (portals within portals), creating multiple undifferentiated instances (see below).

Instead, this PR adds a stable portal element with the class name `rill-portal` to `app.html`. The portal action now appends/removes from this one element and can be placed directly on the element you want to move, making it clearer exactly what is happening. If necessary, additional portal zones can be added to `app.html` and the portal action can take an element or string as an input.

<img width="300" alt="Screenshot 2024-02-29 at 4 28 01 PM" src="https://github.com/rilldata/rill/assets/120223836/306ff40c-592a-4154-90fc-790463c157da">

2024-03-01 02:20 UTC, ericpgreen2 approved these changes
Generally LGTM! But left a couple small comments and hit one bug to resolve before merging.

2024-03-01 02:20 UTC, ericpgreen2 commented on web-common/src/components/modal/ModalContainer.svelte
> +<!-- <Portal> -->
Leftover comment

2024-03-01 02:20 UTC, ericpgreen2 commented on web-local/src/app.html
We should add the same element to `web-admin/src/app.html`

2024-03-01 02:20 UTC, ericpgreen2 commented on web-common/src/features/dashboards/time-series/MeasureZoom.svelte
I'm hitting this error when selecting a subrange on a line chart:

![image](https://github.com/rilldata/rill/assets/14206386/30d54c51-730f-46b5-96ac-124ae0f5ec80)

2024-03-01 13:47 UTC, djbarnwal requested changes
Seeing a few bugs

Dropdowns don't work as before - 
https://github.com/rilldata/rill/assets/4402679/af5d4c5e-e3a1-4f15-a7a3-f3510366e6ed

Scrubbing crashes the app. This is because the "Zoom" button uses the `FloatingElement` component but doesn't require a Portal

2024-03-01 16:47 UTC, briangregoryholmes commented
Just noticed one thing that I think is the cause of the failing test. Looking into it.

2024-03-03 06:57 UTC, djbarnwal reviewed
The zoom button's height is bigger than the container it is placed in. The reason behind using `FloatingElement` for the zoom button was to show the zoom button fully. If you see the zoom button in this branch vs main, you can see the top of the button being cropped

**Main**
<img width="493" alt="image" src="https://github.com/rilldata/rill/assets/4402679/eb55160f-5b96-42c2-8a5e-9c70d6c346aa">

**Branch**
<img width="498" alt="image" src="https://github.com/rilldata/rill/assets/4402679/e75ab1ed-71b0-4052-8745-b10ba2d00af3">

With reference to menus still seeing some weird error state. Jam here - https://jam.dev/c/49e4acb6-3b79-4d47-9b03-0a6c8891b4b1

2024-03-12 07:19 UTC, djbarnwal approved these changes

2024-03-12 13:48 UTC, merged