Add CustomDashboard editing/preview surfaces
rilldata/rill pull request #4249
Opened 2024-03-05 20:30 UTC by briangregoryholmes

Please go the the `Preview` tab and select the appropriate sub-template:

* [Applications](?expand=1&template=applications_template.md)
* [Others](?expand=1&template=fallback_template.md)

2024-03-05 20:36 UTC, briangregoryholmes commented
@ericpgreen2 @mindspank @AdityaHegde 

Here's a PR based on our discussion this morning. Absolutely still in progress, but wanted to to get some initial feedback.

A few notes:

I think the dashboard definition is "narrow" enough that we could easily display this as a two column layout rather than only offering full screen views. I found flipping back and forth to be a little annoying.

I've updated the DashboardComponent definition to have `x`, `y`, `width` and `height` values instead of simply `columns` and `rows`. Naming is absolutely up for discussion, but the general idea is that these are to be provided in grid units.

@AdityaHegde Let me know if I've changed things on the proto side correctly. I really only changed `resources.proto` and the dashboard parser and then ran `make proto.generate`

Not sure if it matters, but the `int64` type for these seems like overkill. Feels like we could make them uint8, but that type isn't recognized in `resources.proto`

2024-03-06 02:19 UTC, ericpgreen2 commented
> I think the dashboard definition is "narrow" enough that we could easily display this as a two column layout rather than only offering full screen views. I found flipping back and forth to be a little annoying.

I'm all for showing this in a two-column layout. These dashboards should be responsive to small screen widths anyways (a current deficiency of the Metrics Explorer, which makes a two-column layout for it less practical at the moment).

In a responsive dev environment, maybe it makes sense to label the screen size somewhere in the Dashboard Preview, with a note/tooltip that says your dashboard layout will be different on different screen sizes.

> I've updated the DashboardComponent definition to have `x`, `y`, `width` and `height` values instead of simply `columns` and `rows`. Naming is absolutely up for discussion, but the general idea is that these are to be provided in grid units.
>
> I also removed the idea of setting the number of rows at the grid level and added a gap property. I didn't really see how setting rows would be used in a way that felt intuitive. I've just set this up to ingest the column count and create a grid that features square cells with a row count equal to whatever the max calculated row would be based on the component definitions.

On first pass, these ergonomics feel good to me! @mindspank, I know you've thought more about the Dashboard YAML, what do you think?

Playing around with it, I'm thinking a toggle to show gridlines on the Dashboard Preview could be really helpful.

2024-03-06 05:27 UTC, AdityaHegde commented
Hey @briangregoryholmes . Yes, the proto files are generated correctly. We could use `uint32` instead of int64.

2024-03-07 15:34 UTC, briangregoryholmes commented
Added grid line toggle.

2024-03-11 04:08 UTC, ericpgreen2 commented
Checked in on the latest progress. At a macro level, the editing experience feels pretty good!

The main item that concerns me is responsiveness. Currently, the grid has the same number of columns for all screen sizes, which leads to dashboard miniaturization on smaller screens. If we were to take any of the in-the-wild custom dashboards that @mindspank shared in Slack, they wouldn't look very good on mobile and you'd have to zoom in to read them. We should outline the options and trade-offs for different approaches.

2024-03-11 05:17 UTC, mindspank commented
In general responsiveness does not work well for dashboards for a few reasons

- order is lost when grid is collapsing
- certain visualization types and information density does not work on smaller screen sizes
- you have different tasks you perform on mobile VS desktop

If we'd want to support mobile then I would suggest you'd had to define a separate grid with different content either as a mode in the dashboard or a different dashboard with a mobile type

2024-03-11 05:23 UTC, mindspank commented
There are also two levels of responsiveness, the grid and the visualization itself. For custom charts we don't have a lot of control but for Rill authored visualizations the different components of a chart should have a priority order and then we would layout (or not layout) depending on available size. 
Such as axis and value labels, label collision and entire axises.

See https://picassojs.studio/#stacked-bar-chart for example

2024-03-26 05:02 UTC, AdityaHegde requested changes

2024-03-26 05:02 UTC, AdityaHegde commented on web-common/src/features/custom-dashboards/VegaLiteRenderer.svelte
> +<script lang="ts">
Can we reuse the render in features/charts ? If it is significantly different, better to rename this component with `Embed` in it.

2024-04-05 21:09 UTC, briangregoryholmes commented on web-common/src/features/custom-dashboards/CustomDashboard.svelte
> +  function handleMouseUp() {
Not seeing where this will leak handlers, but this was refactored a bit in the latest code and that may have addressed your concern.

2024-04-06 23:36 UTC, ericpgreen2 approved these changes
I left a few comments, but generally looks good to be merged and we can iterate in follow-on PRs 👍

2024-04-06 23:36 UTC, ericpgreen2 commented on web-common/src/features/custom-dashboards/DashVegaRenderer.svelte
I see `features/charts/render/VegaLiteRenderer.svelte` is quite similar. Can we consolidate on one of these?

2024-04-08 12:20 UTC, AdityaHegde reviewed
Mostly nits. The issue about chart not rendering is a blocker IMO

2024-04-08 12:20 UTC, AdityaHegde commented on web-common/src/features/custom-dashboards/Chart.svelte
> +      spec={parsedVegaSpec}
DashVegaRenderer seem to want `data` is there a layer missing here? Because of this, I dont see the chart at all even if it is valid.

2024-04-08 12:20 UTC, AdityaHegde commented on web-common/src/features/custom-dashboards/Element.svelte
> +          <Chart {chartName} />
This seem to trigger a rerender of chart while dragging. Would be extremely inefficient on complex charts. Perhaps we could lock it while the mouse is held?

2024-04-08 12:23 UTC, AdityaHegde commented on web-common/src/features/custom-dashboards/CustomDashboard.svelte
> +  function handleMouseUp() {
I think when i reviewed there were manual `addEventListeners` But the new code doesnt have that anymore with `svelte:window` so this is not a concern

2024-04-08 14:36 UTC, briangregoryholmes commented on web-common/src/features/custom-dashboards/Element.svelte
> +  const options = [0, 0.5, 1];
I'll try this out after merge.

2024-04-08 16:14 UTC, merged