Bgh/preview table update
rilldata/rill pull request #4529
Opened 2024-04-07 07:30 UTC by briangregoryholmes

Please go the the `Preview` tab and select the appropriate sub-template:

* [Applications](?expand=1&template=applications_template.md)
* [Others](?expand=1&template=fallback_template.md)

2024-04-16 23:24 UTC, ericpgreen2 approved these changes
Much better performance! Nice work 👏

2024-04-17 10:22 UTC, djbarnwal requested changes
Thanks for the PR Brian. Couple of regressions - 

- The table for model/sources is not styled right
- The column size is not adaptive. I would expect the columns with smaller values and header (in length) to have a thinner column. (Not a blocker but good to have if it doesn't add performance issues)
![image](https://github.com/rilldata/rill/assets/4402679/d53c3ccd-3580-4362-a89e-c121e391c99b)

2024-04-17 13:35 UTC, briangregoryholmes commented
@djbarnwal Got the Firefox one. Column sizes are set variably, but I was applying too much buffer, so that's been addressed as well.

2024-04-18 03:59 UTC, djbarnwal approved these changes

2024-04-18 13:21 UTC, merged