File Explorer: Fix new file names
rilldata/rill pull request #4676
Opened 2024-04-20 00:17 UTC by ericpgreen2

This PR fixes cases where new files were not properly incrementing their names to e.g. `untitled_file_1`. There are a few permutations to handle:
- New blank files in the root directory
- New blank files in subdirectories
- New directories in the root directory
- New directories in subdirectories
- New resource files in their resource-specific directories

The PR also fixes some other CRUD-related errors:
- Removes a no-longer-needed constraint on renaming custom dashboards
- Fixes a console error when deleting files from the root page

2024-04-21 05:41 UTC, himadrisingh commented
/review

2024-04-21 05:43 UTC, ericpgreen2 commented
## Code Review Agent Run Status

- **AI Based Review:** Successful
## Code Review Overview

- **Summary:** This PR introduces several key enhancements and fixes across file management functionalities, including file and directory naming conventions, path normalization, and CRUD operations. It also refines the handling of resource kinds to exclude non-user-facing types, improving the clarity and maintainability of the codebase. The changes are well-structured, addressing both functional bugs and code quality improvements.
- **Code change type:** Bug Fix, Refactoring, Feature Addition
- **Unit tests added:** False
- **[Estimated effort to review ](https://docs.bito.ai/bito-dev-agents/ai-code-review-agent/faqs#what-is-estimated-effort-to-review-in-code-review-output)(1-5, lower is better):** 2, due to the clear structure of changes and the context provided, making it easier to understand the impact and necessity of each change.




 <b> [>>See detailed code suggestions<<](https://github.com/rilldata/rill/pull/4676/files) </b><br>The Bito AI Code Review Agent successfully reviewed 5 files and discovered 1 issue. Please review these issues along with suggested fixes in the [Changed Files](https://github.com/rilldata/rill/pull/4676/files).
## High-level Feedback

 General feedback for improvement includes ensuring comprehensive unit tests for new functionalities and refactoring, adhering to DRY principles especially in repeated logic for path handling, and further optimizing string manipulations for better performance and readability. Leveraging more TypeScript features for type safety and clearer interfaces could also enhance code maintainability.

2024-04-21 05:43 UTC, ericpgreen2 commented on web-common/src/features/file-explorer/new-files.ts
>    await runtimeServicePutFile(instanceId, newPath, {
**Scalability Issue**: The function handleEntityCreate fetches all file names without considering the scalability impact of fetching large datasets, especially in systems with a vast number of files. <br> **Fix**: Cache file names or use a more efficient querying mechanism that can handle large datasets without significant performance degradation. Consider lazy loading or paginating file name fetches. <br> **Code Suggestion**: 
 ```
 +  const allNames = await fetchAllFileNames(queryClient, instanceId, { pagination: true });
 +  // Implement caching mechanism for file names to improve scalability
 ```

2024-04-22 12:03 UTC, AdityaHegde requested changes

2024-04-22 12:03 UTC, AdityaHegde commented on web-common/src/features/entity-management/file-selectors.ts
> +        if (!data.files) {
Would be good to add tests to these. Perhaps just this selector function? Same with the selector function in `useDirectoryNamesInDirectory`

2024-04-23 05:06 UTC, AdityaHegde approved these changes

2024-04-23 05:06 UTC, merged