feat: Global dimension search in metrics view in both rill dev and cloud
rilldata/rill pull request #4905
Opened 2024-05-15 11:03 UTC by AdityaHegde

closes #4882

2024-05-20 21:56 UTC, ericpgreen2 requested changes
Overall it looks pretty good! 

UXQA –
1. If a search query errored, we should say so. Here I received "context deadline exceeded" when searching against a Druid-backed dashboard.
![image](https://github.com/rilldata/rill/assets/14206386/02740044-d0b3-469f-aed4-0740e5c4a33e)
2. There's very poor performance when searching Druid-backed dashboards. Mind opening up a conversation with Platform to confirm the batch query approach, or if they recommend a different query pattern?
3. It'd be nice to submit the form after a pause in typing. If so, subsequent typing should cancel an outstanding request.
4. On an Adbids dashboard in Rill Developer, I searched for "facebook" and the search never finished searching the `Domain` dimension. I see the below error in my browser console.
![image](https://github.com/rilldata/rill/assets/14206386/7c0fb714-c6b0-4638-a24f-642991b60a7a)
![image](https://github.com/rilldata/rill/assets/14206386/41ed3eee-94a6-45e8-9284-fd95b758b64b)
5. When a dimension value is already set as a dashboard filter, it'd be nice if there were an indicative checkmark in the search results.
![image](https://github.com/rilldata/rill/assets/14206386/a20ea5e7-d776-49c5-bf1c-a7ca0190e75b)
6. For parity with the Enterprise application, the previous search input text should be retained when re-opening the search box.
7. In Rill Developer, the search button should be to the left of the Deploy & Edit Metrics buttons.
8. Nit: When there are no results yet, there shouldn't be the extra empty bottom section below the `DropdownMenuSeparator`.
![image](https://github.com/rilldata/rill/assets/14206386/2bce8f22-411a-473c-bf17-9594b2d9b9d5)
9. Nit: After using the down arrow key to focus on the first menu item, I'd like the up arrow key to re-focus on the search input.

2024-05-29 16:42 UTC, ericpgreen2 commented
As mentioned in the demo, let's add a feature flag for this so that we can iterate on the Druid performance in a follow-on PR.

2024-05-30 01:22 UTC, ericpgreen2 approved these changes
Looks good. One more UXQA finding:
- The "x" button shouldn't have this background color:
![image](https://github.com/rilldata/rill/assets/14206386/82dd590f-7671-4ea5-ae25-b6899930f923)

2024-05-30 01:49 UTC, ericpgreen2 commented on package-lock.json
Confirming this `package-lock.json` modification is intended? I'm not seeing any `package.json` changes in this PR.

2024-05-30 05:54 UTC, AdityaHegde commented on package-lock.json
Nope. Will revert

2024-05-30 06:31 UTC, AdityaHegde commented
Merging this behind a feature flag: `dimensionSearch`

2024-05-30 06:31 UTC, merged