Refactor `WatchResourcesClient` response handler
rilldata/rill pull request #5572
Opened 2024-08-30 23:01 UTC by ericpgreen2

Closes https://github.com/rilldata/rill/issues/5480, https://github.com/rilldata/rill-private-issues/issues/591, https://github.com/rilldata/rill-private-issues/issues/628

2024-09-04 13:00 UTC, AdityaHegde requested changes
We are refetching profiling queries for sources and models once when the reconcile starts and once when it ends. I didnt check a lot of edge cases, with the simplification I feel we will miss quite a few of those.

2024-09-05 22:38 UTC, ericpgreen2 commented on web-common/src/features/entity-management/WatchResourcesClient.ts
> +      getRuntimeServiceListResourcesQueryKey(this.instanceId, undefined),
Ah, good point. I made two changes:
1. Return early for the `ProjectParser` resource
2. Check to ensure the `stateVersion` has been incremented. Do you agree/disagree that we should check the `stateVersion` (as opposed to the `version` or `specVersion`)?

2024-09-05 23:21 UTC, ericpgreen2 commented on web-common/src/features/entity-management/WatchResourcesClient.ts
> +            void queryClient.invalidateQueries(
Now that I've added the check that the `stateVersion` has been incremented, this is only refetched once per model edit.

2024-09-05 23:28 UTC, ericpgreen2 commented on web-common/src/features/entity-management/WatchResourcesClient.ts
> +      case V1ResourceEvent.RESOURCE_EVENT_WRITE: {
I only discovered some redundancies/simplifications by removing layers of abstraction. IMO the switch statements are pretty clear. Mind if we keep it flat for now?

2024-09-12 08:37 UTC, AdityaHegde commented on web-common/src/features/entity-management/WatchResourcesClient.ts
> +            void queryClient.invalidateQueries(
Do we really need to invalidate this for every model change? Wont it just be when it is removed/added?

2024-09-12 08:37 UTC, AdityaHegde approved these changes

2024-09-12 08:38 UTC, AdityaHegde commented on web-common/src/features/entity-management/WatchResourcesClient.ts
> +      getRuntimeServiceListResourcesQueryKey(this.instanceId, undefined),
Ya with the new changes `stateVersion` makes more sense.

2024-09-12 14:53 UTC, ericpgreen2 commented on web-common/src/features/entity-management/WatchResourcesClient.ts
> +            void queryClient.invalidateQueries(
Yep, you're right. Just added a check so that it's only invalidated when the `source.state.table` or `model.state.resultTable` changes.

2024-09-12 15:15 UTC, merged