feat: undo zoom
rilldata/rill pull request #5597
Opened 2024-09-03 15:26 UTC by briangregoryholmes

Changes the copy of the chart Zoom UI elements and adds the ability to revert to the previous range via keyboard shortcut or button click.

2024-09-03 17:05 UTC, briangregoryholmes commented
Moving to draft to resolve an outstanding question.

2024-09-03 20:44 UTC, lovincyrus requested changes
Nice QoL changes!

- [ ] Add font-semibold to the hotkeys
- [ ] Consistent copy (1) (Z) Zoom, (2) (⌘ Z) Undo Zoom
- [ ] ⌘Z should have a whitespace in between. Try adding tracking-widest to the span. Ref: https://ui.shadcn.com/docs/components/command
- [ ] Add windows support, Ctrl+Z to undo. Refer to https://github.com/reaviz/reakeys/blob/master/src/utils.ts

2024-09-18 17:38 UTC, lovincyrus requested changes
The undo changes work great! One thing that I noticed, we shouldn't show Zoom (Z) when the interval is invalid.

See screenshot and recording:

![CleanShot 2024-09-18 at 10 36 56@2x](https://github.com/user-attachments/assets/76927f49-7f40-46b6-9e4f-2cf57b18f629)


https://github.com/user-attachments/assets/2d0fe414-6d1b-43ef-9c7a-3b1b6874cd85

2024-09-18 20:03 UTC, lovincyrus approved these changes

2024-09-20 16:03 UTC, merged