feat : SQL expressions for URI in dimensions
rilldata/rill pull request #5603
Opened 2024-09-04 13:02 UTC by k-anshul

https://github.com/rilldata/rill/issues/5282

Allows caller to get URI for a dimension using a measure compute:
```
 {
      "name": "app_site_domain_uri",
      "uri": {
          "dimension": "app_site_domain"
      }
}
```
check `runtime/queries/metricsview_aggregation_test.go -> testMetricsViewsAggregationURI` for detailed request.

2024-09-04 20:40 UTC, mindspank commented
@nishantmonu51 we'd need some tiny frontend changes to make use of the new backend property as well. Are we tracking that anywhere?

2024-09-05 01:37 UTC, k-anshul commented
Hey @mindspank 

Just an FYI that we will change this approach. This has certain limitations.

2024-09-09 12:32 UTC, begelundmuller requested changes

2024-09-09 12:32 UTC, begelundmuller commented on proto/rill/runtime/v1/queries.proto
> +    MetricsViewAggregationMeasureURI uri = 11;
The type name should be `MetricsViewAggregationMeasureComputeURI` for consistency with the other "compute" options.

2024-09-09 12:32 UTC, begelundmuller commented on runtime/metricsview/query.go
> +}
Seems like this isn't used?

2024-09-10 08:59 UTC, begelundmuller approved these changes

2024-09-10 08:59 UTC, merged