feat : Alerts should not wake up idle clickhouse service
rilldata/rill pull request #5787
Opened 2024-09-26 13:51 UTC by k-anshul

closes https://github.com/rilldata/rill/issues/5683

2024-10-22 11:21 UTC, begelundmuller requested changes
Reflecting on the four CH cloud related properties here, I wonder if this overcomplicates things too much.

Maybe we should just keep it simple and change the `AlertsDefaultStreamingRefreshCron` default to every 6 hours (or something like that) when the DB host matches CH cloud? It's easier to override a cron tab than set all these CH cloud environment variables.

And maybe additionally request a feature from CH that lets us check if the database is scaled down using the credentials in the CH DSN?

2024-10-22 11:21 UTC, begelundmuller commented on runtime/drivers/clickhouse/olap.go
> +	}
I think caching for 10 mins is too long, makes it too likely to lead to a feedback loop that keeps it alive

2024-10-22 11:21 UTC, begelundmuller commented on runtime/drivers/clickhouse/clickhouse.go
> +	ServiceID      string `mapstructure:"service_id"`
These fields should probably be prefixed with `cloud_` to clarify that they are CH Cloud specific.

2024-10-23 12:11 UTC, k-anshul commented
I understand the issues in setting up four different properties that is why I initially rejected this solution to check for service status.

But I am somewhat sceptical about changing the alert check duration to 6 hours by default for all clickhouse cloud, given our positioning as operational BI. For some customers 6 hours can mean that users miss important alerts. 

May be we show this as a message on UI when users are configuring alerts and ask users to change alert duration check. The note can be somewhat `Caution : Rill alert checks can keep the olap service active and prevent it from scaling down to 0. Consider changing when alerts are checked by setting this property...`

We can also be smart about when this is shown. The decision can be taken on two factors:
1. Table should be streaming.
2. OLAP can scale down to zero. We can expose this property as part of the `ListConnectors`.

2024-10-23 12:13 UTC, k-anshul commented
For users who have their important data in clickhouse cloud, it is possible that their service never scales to zero. For hobbyist users, it will nudge them to configure alerts check correctly.
If users still want better status checks we can add the actual API based solution.

2024-10-23 12:48 UTC, begelundmuller commented
Ultimately the default interval is going to be a trade-off either way. The optimal interval for someone with an always-on cluster is going to be different than for people with one that's mostly scaled to zero.

However I think the current default of 10 mins is definitely optimized for always-on (like Druid), and will not be desirable for folks that scale to zero frequently. If you think 6 hours is too slow, then how about changing the default to maybe 1hr for ClickHouse Cloud?

I think the best we can do is pick a reasonable default and then ask people to override it for their use case – if we make sure to expose the right config keys for overriding, then we can defer the decision of how to prompt for it to the product folks (please follow up with that question in #team-product).

2025-01-14 16:04 UTC, begelundmuller commented
Closing this PR because it has been open a long time and probably requires a different approach. If the issue gets higher priority later, we can revisit this work.

2025-01-14 16:04 UTC, closed without merging