User and user group management UI
rilldata/rill pull request #5793
Opened 2024-09-27 00:10 UTC by lovincyrus

https://www.notion.so/rilldata/Dev-Notes-10dba33c8f578038a199f257639c577e

https://www.figma.com/design/Qt6EyotCBS3V6O31jVhMQ7/RILL-Latest?node-id=16418-864914&node-type=frame&t=4877tB4jsjaLhZeO-0

https://github.com/user-attachments/assets/ea22bffa-e6ee-4ab3-b2c2-f12c4de59a78

2024-10-04 00:17 UTC, lovincyrus commented
The org settings page will be released together with these changes. cc: @AdityaHegde 

![CleanShot 2024-10-03 at 17 15 39@2x](https://github.com/user-attachments/assets/06c53adc-fd6d-4b1f-afa0-9a316e98e850)

2024-10-04 23:27 UTC, lovincyrus commented on web-admin/src/routes/[organization]/-/users/+page.svelte
> +        //   keepProjectRoles: false,
qq: do we know if we strip away users' project roles when we remove an org user? cc: @AdityaHegde @begelundmuller

2024-10-07 23:04 UTC, ericpgreen2 requested changes
Much needed functionality! Overall, this is great. Here's the start of a review.

UXQA:
1. For consistency with the Project page's sub-pages, I'd wouldn't expect to see the horizontal line separating the header's top & bottom rows:
    <img width="1920" alt="image" src="https://github.com/user-attachments/assets/44522707-ff20-4a1c-8fe0-4aa635093889">
2. Every time I go to the user page, my Avatar is a different color
    <img width="293" alt="image" src="https://github.com/user-attachments/assets/ee66661c-f01b-4ccf-8158-25d1c40a24a4">
    <img width="383" alt="image" src="https://github.com/user-attachments/assets/e751a3be-c70f-4118-9135-26587f23c5d8">
3. What's the effect of setting an Org's description? If there is an effect, can we say so in a tooltip? If there isn't one, can we remove it? 
    <img width="864" alt="image" src="https://github.com/user-attachments/assets/64ce7f7b-871d-4749-8324-35adbb3b9c86">
4. When I create an email pill, clicking "Invite" to submit the form adds an extra line in the text box as a side effect. [Jam](https://jam.dev/c/02974f14-1db6-4ca1-8608-e80da5d2fd12).
5. I noticed that Viewers are unable to see the Users page. They should also be able to see some read-only version of the table, so they can know who their teammates are (especially who are the Admins). This could go in a follow-on PR.
6. I didn't realize that these Role cells had dropdown menus until I hovered over them. Is there supposed to be a border around each role?
    <img width="130" alt="image" src="https://github.com/user-attachments/assets/84f4e515-e777-42d5-a8a3-b3aba0f838bc">

2024-10-07 23:36 UTC, lovincyrus commented
> 1. For consistency with the Project page's sub-pages, I'd wouldn't expect to see the horizontal line separating the header's top & bottom rows:
>    <img alt="image" width="1920" src="https://private-user-images.githubusercontent.com/14206386/374351174-44522707-ff20-4a1c-8fe0-4aa635093889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDM5NTgsIm5iZiI6MTcyODM0MzY1OCwicGF0aCI6Ii8xNDIwNjM4Ni8zNzQzNTExNzQtNDQ1MjI3MDctZmYyMC00YTFjLThmZTAtNGFhNjM1MDkzODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYTBlZTAzZGMzODZjYjNjNmVjODI2NTI0NWI4ZjAzMDRlNWY5MzhkNmNiZjhiNmJkYTdmMTM5MTA1YzFhMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gcQ17zKrtUyUxznop1YJLAtjAWR4bHte2E6KpCCC0W8">

I'm afraid I don't have context for this. This was previously implemented in https://github.com/rilldata/rill/pull/5458 and the changeset of this PR uncomments the changes.

Can you confirm if this is the correct behavior of the horizontal line? @jkhwu 

https://github.com/user-attachments/assets/1d73f904-44a8-4dde-b9c0-347d37eba122

2024-10-07 23:36 UTC, lovincyrus commented
> 2\. Every time I go to the user page, my Avatar is a different color
>     <img alt="image" width="293" src="https://private-user-images.githubusercontent.com/14206386/374351629-ee66661c-f01b-4ccf-8158-25d1c40a24a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDM5NTgsIm5iZiI6MTcyODM0MzY1OCwicGF0aCI6Ii8xNDIwNjM4Ni8zNzQzNTE2MjktZWU2NjY2MWMtZjAxYi00Y2NmLTgxNTgtMjVkMWM0MGEyNGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMzEyNjY3YTNmMDM3ZTIxNGE0MWFmOTczODM5ZGEzNmIyNTdiZTQ3ZWY0YTVkNDU3NTVlNDJmNTE5ZTZjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ygiTbhPKRO7yVr4-RVFwypUY5ZjpHY0yuYO0c83RuhM">
>     <img alt="image" width="383" src="https://private-user-images.githubusercontent.com/14206386/374351588-e751a3be-c70f-4118-9135-26587f23c5d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDM5NTgsIm5iZiI6MTcyODM0MzY1OCwicGF0aCI6Ii8xNDIwNjM4Ni8zNzQzNTE1ODgtZTc1MWEzYmUtYzcwZi00MTE4LTkxMzUtMjY1ODdmMjNjNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTE2MmUzNjA4NDFmNmNkNmM0YzRiMTg1YzQ5M2IwZmZmMWM2MjJmYjM2MjQ4Njg0NGViYjE3NzRlNDA4YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CXSWxUvJAdrDYe8XVF2AesI3SvN_bNhYffQw6rWL7fI">

This is intentional.

2024-10-07 23:39 UTC, lovincyrus commented
> 3\. What's the effect of setting an Org's description? If there is an effect, can we say so in subtext? If there isn't one, can we remove it?
>     <img alt="image" width="864" src="https://private-user-images.githubusercontent.com/14206386/374351993-64ce7f7b-871d-4749-8324-35adbb3b9c86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDM5NTgsIm5iZiI6MTcyODM0MzY1OCwicGF0aCI6Ii8xNDIwNjM4Ni8zNzQzNTE5OTMtNjRjZTdmN2ItODcxZC00NzQ5LTgzMjQtMzVhZGJiM2I5Yzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNmMxMjE1ZTA2YWMzYzQ5MGNkZjNjNTM0YmZlODU3NjBkODA3YjQxYjI0ZWZhOTJiYjg3YzVhYjAxYWU3MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kR3m1-5hOBcFXo_L42JTiwWsgVmP0hgCOtrDF5HH-9A">

This is also a changeset from https://github.com/rilldata/rill/pull/5458

https://www.figma.com/design/Qt6EyotCBS3V6O31jVhMQ7/RILL-Latest?node-id=11202-427942&node-type=frame&t=WjZyoufpATOEltFj-0

Should we remove the org description? @jkhwu

2024-10-07 23:41 UTC, lovincyrus commented
> 6\. I didn't realize that these Role cells had dropdown menus until I hovered over them. Is there supposed to be a border around each role?
>     <img alt="image" width="130" src="https://private-user-images.githubusercontent.com/14206386/374354545-84f4e515-e777-42d5-a8a3-b3aba0f838bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDQ1OTAsIm5iZiI6MTcyODM0NDI5MCwicGF0aCI6Ii8xNDIwNjM4Ni8zNzQzNTQ1NDUtODRmNGU1MTUtZTc3Ny00MmQ1LWE4YTMtYjNhYmEwZjgzOGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMzgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTg2Y2EyYzg0MzUwMWM4NzllZTQzZmJhN2QwNjBlNzJmZTJmYzlmMTY0MGZlOTYyNTc1ZjQ2NWU5NmJkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FUSfwWsHolvKQn6AGgCT4NtyDOrlWx65gwmSxxlvfbY">

A chevron icon will be added for this!

2024-10-07 23:52 UTC, lovincyrus commented on scripts/tsc-with-whitelist.sh
> +web-common/src/components/table/tanstack-table-column-meta.ts: error TS1484
This was failing a github action check. Reverted for testing

2024-10-08 01:13 UTC, jkhwu commented
> Should we remove the org description?
I believe we included org description because it can be set in the CLI, but I'm not sure. If it's not a CLI function I'm pretty sure we can remove it, but if it is, I'll defer on whether it's ok to remove to @ericokuma

> Can you confirm if this is the correct behavior of the horizontal line? 
Confirming that we intended for there to only be one horizontal divider, underneath the tabs if there are tabs to display (for viewers they may only see that line under the top header. This is as shown in the mocks.

> Every time I go to the user page, my Avatar is a different color.
My expectation would be that color assignment to each user is randomized, but that once assigned, that color stays with the user (until some future day when we allow users to sub in custom pics, or we just use their Google one)

2024-10-08 15:14 UTC, lovincyrus commented on scripts/tsc-with-whitelist.sh
> +web-common/src/components/table/tanstack-table-column-meta.ts: error TS1484
![CleanShot 2024-10-08 at 08 13 29@2x](https://github.com/user-attachments/assets/8a7765b8-6f18-49de-bd94-6fa056e75bca)

https://github.com/rilldata/rill/actions/runs/11238307297/job/31242754917?pr=5793

2024-10-08 15:33 UTC, eokuma commented
> > 2. Every time I go to the user page, my Avatar is a different color
> > <img alt="image" width="293" src="https://private-user-images.githubusercontent.com/14206386/374351629-ee66661c-f01b-4ccf-8158-25d1c40a24a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDM5NTgsIm5iZiI6MTcyODM0MzY1OCwicGF0aCI6Ii8xNDIwNjM4Ni8zNzQzNTE2MjktZWU2NjY2MWMtZjAxYi00Y2NmLTgxNTgtMjVkMWM0MGEyNGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMzEyNjY3YTNmMDM3ZTIxNGE0MWFmOTczODM5ZGEzNmIyNTdiZTQ3ZWY0YTVkNDU3NTVlNDJmNTE5ZTZjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ygiTbhPKRO7yVr4-RVFwypUY5ZjpHY0yuYO0c83RuhM">
> > <img alt="image" width="383" src="https://private-user-images.githubusercontent.com/14206386/374351588-e751a3be-c70f-4118-9135-26587f23c5d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDM5NTgsIm5iZiI6MTcyODM0MzY1OCwicGF0aCI6Ii8xNDIwNjM4Ni8zNzQzNTE1ODgtZTc1MWEzYmUtYzcwZi00MTE4LTkxMzUtMjY1ODdmMjNjNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTE2MmUzNjA4NDFmNmNkNmM0YzRiMTg1YzQ5M2IwZmZmMWM2MjJmYjM2MjQ4Njg0NGViYjE3NzRlNDA4YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CXSWxUvJAdrDYe8XVF2AesI3SvN_bNhYffQw6rWL7fI">
> 
> This is intentional.

Oh, I would also expect the avatar color to be the same each time

2024-10-08 15:36 UTC, eokuma commented
> > Should we remove the org description?
> > I believe we included org description because it can be set in the CLI, but I'm not sure. If it's not a CLI function I'm pretty sure we can remove it, but if it is, I'll defer on whether it's ok to remove to @ericokuma
> 
> > Can you confirm if this is the correct behavior of the horizontal line?
> > Confirming that we intended for there to only be one horizontal divider, underneath the tabs if there are tabs to display (for viewers they may only see that line under the top header. This is as shown in the mocks.
> 
> > Every time I go to the user page, my Avatar is a different color.
> > My expectation would be that color assignment to each user is randomized, but that once assigned, that color stays with the user (until some future day when we allow users to sub in custom pics, or we just use their Google one)

I agree with the all the above. 

Also we can remove description (though we designed it because it is part of the CLI function). @ericpgreen2, what's your concern with having a description field?

2024-10-08 15:52 UTC, lovincyrus commented on web-common/src/components/button/Button.svelte
>    }
https://github.com/rilldata/rill/pull/5793/commits/4a13ec6def5f72f4b6a72ebdb8a0455a4991a371

2024-10-08 16:00 UTC, lovincyrus commented
> > > 2. Every time I go to the user page, my Avatar is a different color
> > > 
> > > <img alt="image" width="293" src="https://private-user-images.githubusercontent.com/14206386/374351629-ee66661c-f01b-4ccf-8158-25d1c40a24a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDM5NTgsIm5iZiI6MTcyODM0MzY1OCwicGF0aCI6Ii8xNDIwNjM4Ni8zNzQzNTE2MjktZWU2NjY2MWMtZjAxYi00Y2NmLTgxNTgtMjVkMWM0MGEyNGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMzEyNjY3YTNmMDM3ZTIxNGE0MWFmOTczODM5ZGEzNmIyNTdiZTQ3ZWY0YTVkNDU3NTVlNDJmNTE5ZTZjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ygiTbhPKRO7yVr4-RVFwypUY5ZjpHY0yuYO0c83RuhM">
> > > <img alt="image" width="383" src="https://private-user-images.githubusercontent.com/14206386/374351588-e751a3be-c70f-4118-9135-26587f23c5d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDM5NTgsIm5iZiI6MTcyODM0MzY1OCwicGF0aCI6Ii8xNDIwNjM4Ni8zNzQzNTE1ODgtZTc1MWEzYmUtYzcwZi00MTE4LTkxMzUtMjY1ODdmMjNjNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTE2MmUzNjA4NDFmNmNkNmM0YzRiMTg1YzQ5M2IwZmZmMWM2MjJmYjM2MjQ4Njg0NGViYjE3NzRlNDA4YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CXSWxUvJAdrDYe8XVF2AesI3SvN_bNhYffQw6rWL7fI">
> > 
> > 
> > This is intentional.
> 
> Oh, I would also expect the avatar color to be the same each time

To persist a color, we'd need to add a new field to User so the returning user will always have a persistent color. Is that what we want to take on? cc: @ericpgreen2 

![CleanShot 2024-10-08 at 08 58 01@2x](https://github.com/user-attachments/assets/d7313614-73d4-4205-8620-4c34eb557090)

2024-10-08 18:14 UTC, ericpgreen2 commented
> To persist a color, we'd need to add a new field to User so the returning user will always have a persistent color. Is that what we want to take on? cc: @ericpgreen2

Simpler, we could deterministically select a color client-side based on the user name or email.

2024-10-08 18:15 UTC, ericpgreen2 commented
> Also we can remove description (though we designed it because it is part of the CLI function). @ericpgreen2, what's your concern with having a description field?

No concern with the description field, just thought we could hide it for now if it's not used anywhere yet.

2024-10-08 19:51 UTC, lovincyrus commented
> > Also we can remove description (though we designed it because it is part of the CLI function). @ericpgreen2, what's your concern with having a description field?
> 
> No concern with the description field, just thought we could hide it for now if it's not used anywhere yet.

Removed

2024-10-08 20:56 UTC, eokuma commented
> > > Also we can remove description (though we designed it because it is part of the CLI function). @ericpgreen2, what's your concern with having a description field?
> > 
> > 
> > No concern with the description field, just thought we could hide it for now if it's not used anywhere yet.
> 
> Removed

Sorry Cyrus, Eric, Janet, and I synced, and we decided to keep the description field

2024-10-10 23:15 UTC, ericpgreen2 approved these changes
LGTM! Left some code comments & here are some UXQA items:
1. The Avatar is using a random color in favor of my Google avatar.
2. The users table is not showing users directly added to a project (but if this is meant for a follow-on PR, that's ok)

2024-10-10 23:15 UTC, ericpgreen2 commented on web-admin/src/features/organizations/users/AvatarCircleList.svelte
Naming nit: I'm not sure I follow what makes this a "List"

2024-10-10 23:15 UTC, ericpgreen2 commented on web-admin/src/routes/[organization]/-/users/groups/+page.svelte
> +  async function handleRename(groupName: string, newName: string) {
Similarly, this (and the other User Group actions in this file) is getting prop-drilled: `+page.svelte` -> `OrgGroupsTable.svelte` -> `OrgGroupsActionCell.svelte` -> `EditUserGroupDialog.svelte`

2024-10-10 23:15 UTC, ericpgreen2 commented on web-common/src/components/table/BasicTable.svelte
Great to have this!

2024-10-11 18:01 UTC, lovincyrus commented on web-common/src/components/button/Button.svelte
> +  }
removed and tested - this is needed since there is another way to set danger class using status === 'error'.

2024-10-11 18:09 UTC, merged