fix: bookmark query by doing a case insensitive query
rilldata/rill pull request #6093
Opened 2024-11-15 15:25 UTC by AdityaHegde

Our top navigation bar uses lower case resource name so if a bookmark was created with original case and navigated to using top bar the older bookmarks were not found anymore.

Making the bookmark query case insensitive since resource name is already case insensitive in our system.

2024-11-15 16:27 UTC, begelundmuller requested changes
Thanks! Can you also update the `bookmarks_search_idx` to index on `lower(resource_name)` and consider if other indexes would make sense to add?

2024-11-18 06:37 UTC, AdityaHegde commented
Updated `bookmarks_search_idx`. Do you mean other indices or other columns in this index?

For other columns it doesnt make sense, the only one we could possibly do it is `resource_kind` but since we use constants for that it would be overkill.

For other indices, for sure. Lets take as a follow up of this PR since it would need some thorough check.

2024-11-19 11:39 UTC, begelundmuller approved these changes

2024-11-19 11:39 UTC, begelundmuller commented on admin/database/postgres/migrations/0053.sql
> +CREATE INDEX bookmarks_search_idx ON bookmarks (project_id, lower(resource_name), resource_kind);
```suggestion
CREATE INDEX bookmarks_search_idx ON bookmarks (project_id, resource_kind, lower(resource_name));
```

2024-11-19 12:05 UTC, merged