Separate State dir for cloud/e2e
rilldata/rill pull request #6291
Opened 2024-12-17 08:26 UTC by himadrisingh

2024-12-17 22:30 UTC, ericpgreen2 requested changes
I'm getting this out-of-memory error with `./rill devtool start e2e --reset`, but not with `rill devtool start e2e --reset`:
![image](https://github.com/user-attachments/assets/cc46bc4e-74b7-4b20-a998-7b9e5b1d3cd6)

The code generally LGTM, but given it's Go, CC'ing @begelundmuller for his eyes on this too.

2024-12-19 19:12 UTC, begelundmuller commented on cli/cmd/devtool/start.go
> +	stateDir := lookupDotenv("RILL_STATE_DIRECTORY")
All our other env variables have the format `RILL_<service>_<name>`, so should this perhaps be `RILL_DEVTOOL_STATE_DIRECTORY`? Or we could pass it with a flag to the `rill devtool start` instead?

2024-12-19 19:16 UTC, begelundmuller commented
> I'm getting this out-of-memory error with `./rill devtool start e2e --reset`, but not with `rill devtool start e2e --reset`

Weird, could it be the state directory is not created? A Google search indicates it's from SQLite and can be due to a number of reasons about not being able to create/access the file. E.g. see here: https://community.grafana.com/t/problems-with-error-checking-db-error-checking-for-valid-sqlite-file-unable-to-open-database-file-out-of-memory-14/92025

2024-12-20 03:56 UTC, himadrisingh reviewed
rename RILL_DEVTOOL_STATE_DIRECTORY

2024-12-20 03:56 UTC, himadrisingh commented on cli/cmd/devtool/data/cloud-deps.docker-compose.yml
> +      - ../../../../${RILL_STATE_DIRECTORY}/postgres:/var/lib/postgresql/data
```suggestion
      - ../../../../${RILL_DEVTOOL_STATE_DIRECTORY}/postgres:/var/lib/postgresql/data
```

2024-12-20 03:56 UTC, himadrisingh commented on cli/cmd/devtool/data/cloud-deps.docker-compose.yml
> +      - ../../../../${RILL_STATE_DIRECTORY}/stripe-config.toml:/etc/stripe-config.toml
```suggestion
      - ../../../../${RILL_DEVTOOL_STATE_DIRECTORY}/stripe-config.toml:/etc/stripe-config.toml
```

2024-12-20 03:56 UTC, himadrisingh commented on cli/cmd/devtool/start.go
> +	stateDir := lookupDotenv("RILL_STATE_DIRECTORY")
```suggestion
	stateDir := lookupDotenv("RILL_DEVTOOL_STATE_DIRECTORY")
```

2024-12-20 03:56 UTC, himadrisingh commented on cli/cmd/devtool/start.go
> +	stateDir := lookupDotenv("RILL_STATE_DIRECTORY")
```suggestion
	stateDir := lookupDotenv("RILL_DEVTOOL_STATE_DIRECTORY")
```

2024-12-20 03:56 UTC, himadrisingh commented on cli/cmd/devtool/start.go
> +	stateDir := lookupDotenv("RILL_STATE_DIRECTORY")
```suggestion
	stateDir := lookupDotenv("RILL_DEVTOOL_STATE_DIRECTORY")
```

2024-12-20 03:56 UTC, himadrisingh commented on cli/cmd/devtool/start.go
> +	stateDir := lookupDotenv("RILL_STATE_DIRECTORY")
```suggestion
	stateDir := lookupDotenv("RILL_DEVTOOL_STATE_DIRECTORY")
```

2024-12-31 23:58 UTC, ericpgreen2 commented
> Weird, could it be the state directory is not created? A Google search indicates it's from SQLite and can be due to a number of reasons about not being able to create/access the file. E.g. see here: https://community.grafana.com/t/problems-with-error-checking-db-error-checking-for-valid-sqlite-file-unable-to-open-database-file-out-of-memory-14/92025

Yeah, that's possible. Working for me now!

2024-12-31 23:59 UTC, ericpgreen2 commented
This is tangential and for another PR, but I just discovered that we should also be able to upload `.env` files for the `e2e` environment. See:
<img width="905" alt="image" src="https://github.com/user-attachments/assets/2017bf5c-787c-4406-be37-fd643ddc39c1" />

2024-12-31 23:59 UTC, ericpgreen2 approved these changes

2025-01-01 00:06 UTC, ericpgreen2 requested changes

2025-01-01 00:06 UTC, ericpgreen2 commented on cli/cmd/devtool/start.go
> +	args := []string{"run", "cli/main.go", "start", stateDir, "--no-ui", "--debug", "--allowed-origins", "http://localhost:3001"}
Regression: `rill devtool start local` should use the `dev-project` directory.

2025-01-01 12:10 UTC, himadrisingh commented on cli/cmd/devtool/start.go
> +	args := []string{"run", "cli/main.go", "start", stateDir, "--no-ui", "--debug", "--allowed-origins", "http://localhost:3001"}
looks like rill always uses `dev-project`, will revert the change

2025-01-01 12:11 UTC, himadrisingh commented on cli/cmd/devtool/start.go
> +	args := []string{"run", "cli/main.go", "start", stateDir, "--no-ui", "--debug", "--allowed-origins", "http://localhost:3001"}
```suggestion
	args := []string{"run", "cli/main.go", "start", stateDirLocal, "--no-ui", "--debug", "--allowed-origins", "http://localhost:3001"}
```

2025-01-01 12:12 UTC, himadrisingh commented on cli/cmd/devtool/start.go
>  	rillGithubURL  = "https://github.com/rilldata/rill"
```suggestion
	stateDirLocal  = "dev-project"
	rillGithubURL  = "https://github.com/rilldata/rill"
```

2025-01-01 17:11 UTC, himadrisingh commented on cli/cmd/devtool/start.go
> +	args := []string{"run", "cli/main.go", "start", stateDir, "--no-ui", "--debug", "--allowed-origins", "http://localhost:3001"}
done!

2025-01-02 02:31 UTC, ericpgreen2 requested changes
Running `./rill devtool start e2e --reset` deletes my `cloud` state directory (`dev-cloud-state`). I'd expect the `--reset` flag would only clear the state directory for the chosen environment.

2025-01-02 03:39 UTC, himadrisingh commented
that is strange, it should be checking the .env to get the state dir
https://github.com/rilldata/rill/pull/6291/files#diff-5c40fcfa49d7699fa05419f4136141b7df48fcc015e7625137228f3b6588b5f4R388-R390

2025-01-02 03:40 UTC, himadrisingh commented
oh, looks like the order of tasks is diff when `--reset` is called.

2025-01-02 22:02 UTC, ericpgreen2 approved these changes

2025-01-02 22:02 UTC, merged