Feat: *new* Canvas dashboard
rilldata/rill pull request #6294
Opened 2024-12-17 16:46 UTC by djbarnwal

2025-01-03 00:31 UTC, ericpgreen2 requested changes
Overall, nice progress! I kicked off a [UXQA doc here](https://www.notion.so/rilldata/Canvas-2-0-16fba33c8f5780f98924c3ace91bc76e). I'd be fine if we took most of the UXQA items in follow-up PRs, but IMO the code comments would be nice to resolve before merge – else I fear we'll lose them.

2025-01-03 00:31 UTC, ericpgreen2 commented on web-common/src/features/canvas/stores/canvas-stores.ts
> +  function addEntity(name: string) {
Nit: "addCanvas" and "removeCanvas" would be more semantic. I'd expect "addEntity" only if the entity type were variable.

2025-01-03 00:31 UTC, ericpgreen2 commented on web-common/src/features/canvas/stores/canvas-time-control.ts
Nice to see the independent stores!

2025-01-03 00:31 UTC, ericpgreen2 commented on web-common/src/features/canvas/stores/syncCanvasState.ts
> +    return { isFetching: false, error: false };
When we get around to implementing this state sync, could we move it into the `CanvasEntity` class itself? Then we can encapsulate/colocate all logic around state there. If so, we could probably remove this file altogether (though, just need to find a better place for the `canvasEntities.addCanvas(canvasName)` call).

2025-01-03 00:31 UTC, ericpgreen2 commented on web-common/src/features/canvas/state-managers/types.ts
I don't see these types used anywhere. Can we delete this file?

2025-01-03 00:31 UTC, ericpgreen2 commented on web-common/src/features/canvas/state-managers/StateManagersProvider.svelte
Here too, ideally we move away from the React provider pattern. E.g., this component could be replaced by a function `initializeStateManagers()`.

2025-01-03 00:37 UTC, ericpgreen2 commented on web-common/src/features/canvas/components/BaseCanvasComponent.ts
Related, could we move `features/canvas/components` to `features/components`. Ultimately, it should be possible to embed individual components (not requiring a wrapping canvas). Then, at some point, we could migrate toward the long-term ideal of embedding these components into the Explore dashboard.

2025-01-03 00:39 UTC, ericpgreen2 commented on web-common/src/features/canvas/components/BaseCanvasComponent.ts
If any prefix, I think the prefix should be "DashboardComponent", which would better imply that these components can be embedded into either the Canvas dashboards or the Explore dashboards.

2025-01-03 12:07 UTC, djbarnwal commented on web-common/src/features/canvas/components/BaseCanvasComponent.ts
With regards to moving `features/canvas/components` to `features/components` - 
We previous had a `features/templates` folder (still exists but lot of templates have been removed, goal is remove it all in future). It unnecessarily made it complex to use vega charts in TDD and in Canvas. I feel the right approach is to keep building blocks for common components inside `src/components` and then they can be used by Canvas or Explore as needed. These components would have to handle two different types of state managers so feels better to have a copy of their own for simplicity.

2025-01-03 12:12 UTC, djbarnwal commented on web-common/src/features/canvas/components/BaseCanvasComponent.ts
> +  pathInYAML: (string | number)[] = [];
When accessing an array inside a YAML with nested objects, we can use index as well. 

More at https://eemeli.org/yaml/v1/#collections There's no direct definition added but usage is mentioned in the docs.

2025-01-03 16:30 UTC, djbarnwal commented on web-common/src/features/canvas/components/charts/util.ts
> +      return generateVLBarChartSpec(chartConfig, data);
The cases are type safe. Removed `default`

2025-01-03 16:31 UTC, djbarnwal commented on web-common/src/features/templates/types.ts
Ideally we will be getting rid of `templates`. More here https://github.com/rilldata/rill/pull/6294#discussion_r1901725954

2025-01-03 16:32 UTC, ericpgreen2 commented on web-common/src/features/canvas/components/BaseCanvasComponent.ts
Ideally, IMO, we consider `src/components` as the Rill design system, which, in theory, could be published for anyone to use. Each component should be isolated/encapsulated and should not have dependencies on Rill systems (like a Rill runtime or a Rill app's state management system).

We _almost_ adhere to that ideal today. Except, for example, I see that the `src/components/preview-table/ConnectedPreviewTable.svelte` fetches data from a Rill runtime.

So, if the building blocks you're proposing do not include Rill data fetching or Rill state management, then, yeah, I think it's a great idea to put them in `src/components`. If they do include Rill data fetching or state management, then I'd vote for putting them in `src/features/components`.

2025-01-03 16:45 UTC, ericpgreen2 commented on web-common/src/features/canvas/components/BaseCanvasComponent.ts
> +  pathInYAML: (string | number)[] = [];
Ok I see now. Maybe a comment with an example path would help

2025-01-03 18:47 UTC, djbarnwal commented on web-common/src/features/canvas/components/charts/types.ts
> +  title: string;
This is for internal reference and is not used to for the YAML. This is used for rendering of the chart selectors

2025-01-03 18:49 UTC, djbarnwal commented on web-common/src/features/canvas/components/charts/types.ts
> +  y?: FieldConfig;
Component specific changes would be addressed in follow up PRs. The goal of this PR is create a good base for canvas against which multiple streams of canvas related tasks can be taken up simultaneously.

2025-01-03 18:58 UTC, djbarnwal commented on web-common/src/features/canvas/stores/CanvasStateProvider.svelte
Removed this component and moved it's logic upstream

2025-01-03 19:02 UTC, djbarnwal commented on web-common/src/features/canvas/CanvasThemeProvider.svelte
For now I am using the same patterns and reusing the wrapper components from Explore. I would prefer to visit this once we have checked all the P0s.

2025-01-06 06:43 UTC, AdityaHegde commented on web-common/src/features/canvas/components/BaseCanvasComponent.ts
> +export abstract class BaseCanvasComponent<T> implements CanvasComponent<T> {
Feels a little weird having an interface and an abstract class. We should have a single layer.

Another options is to move to `has-a` relation with child components being a member. These classes will only have minSize, defaultSize, isValid, inputParams and newComponentSpec.

2025-01-06 06:43 UTC, AdityaHegde commented on web-common/src/features/canvas/components/ComponentRenderer.svelte
> +  {#if renderer === "kpi"}
Can we move to a map instead of if-else. Will be cleaner once we have a lot of components. Similar to how we select the workspace here: https://github.com/rilldata/rill/blob/main/web-local/src/routes/(application)/(workspace)/files/%5B...file%5D/%2Bpage.svelte#L56

2025-01-06 06:43 UTC, AdityaHegde commented on web-common/src/features/workspaces/CanvasWorkspace.svelte
> +{:else if allErrors.length}
This should not be in the else. Since both `code` and `viz` are in the other if body, if there are errors user cannot edit the canvas in rill-dev at all.

2025-01-06 06:43 UTC, AdityaHegde commented on web-common/src/features/workspaces/CanvasWorkspace.svelte
> +                <ErrorPage
Same here. We should show the error at the bottom of the page and still keep the editor up so that the user can fix issues.

2025-01-06 07:24 UTC, djbarnwal commented on runtime/compilers/rillv1/parse_component.go
> +	// We generally treat the renderer props as untyped, but since "metrics_view" is a very common field,
@begelundmuller

2025-01-06 08:47 UTC, djbarnwal commented on web-common/src/features/workspaces/CanvasWorkspace.svelte
> +                <ErrorPage
This seems to be fine right? The main error page is only shown when selected view is `viz` ?

2025-01-07 17:05 UTC, begelundmuller commented on runtime/compilers/rillv1/parse_component.go
> +	// We generally treat the renderer props as untyped, but since "metrics_view" is a very common field,
Fixed!

2025-01-09 03:43 UTC, ericpgreen2 approved these changes
Approving to unblock the merge

2025-01-09 08:09 UTC, merged