feat: Add new rill time parser backend support
rilldata/rill pull request #6326
Opened 2024-12-23 06:21 UTC by AdityaHegde

- [x] Add module for parsing rill time syntax in backend.
- [ ] Support syntax like, `2024-12-15,+5d`
- [ ] Add `ResolveTime` to return start and end times based on minTime, maxTime and now for a metrics view.
- [ ] Replace usage of old duration parser.
- [ ] Map old format to new format
- [ ] Add API to resolve times for a list of rill-times.
- [ ] Add a lot more tests.

2025-01-08 11:24 UTC, k-anshul requested changes

2025-01-08 11:24 UTC, k-anshul commented on runtime/pkg/metricssql/time_range_parser.go
> +func (q *query) getMinTime(ctx context.Context, colName string) (time.Time, error) {
Nite : Can directly use `metricsview.Executor.GetMinTime` ? The existing code does not use `watermark` from `Executor` because the implementations are somewhat different.

2025-01-08 11:24 UTC, k-anshul commented on runtime/pkg/metricssql/time_range_parser.go
> +	for result.Next() {
Also need to check for `result.Err()`

2025-01-08 11:24 UTC, k-anshul commented on runtime/pkg/metricssql/time_range_parser.go
> +	rt, unit, colName, err := parseTimeRangeArgs(node.Args)
More of a product call but given the unit can now be expressed with the new time range syntax, may be we should just omit the unit from `time_range_start` and `time_range_end` definition.
I don't think they are used externally so should be okay to make a backward incompatible change.

2025-01-09 15:56 UTC, begelundmuller requested changes

2025-01-09 15:56 UTC, begelundmuller commented on runtime/compilers/rillv1/parse_explore.go
> +			if ctr.Offset != "" {
Consider having a `rilltime.ParseCompatibility(ctr.Range, ctr.Offset)` function – this would avoid duplicating the error handling if `isoOffset` is combined with the new format, and also avoid exposing the `IsNewFormat` outside the package

2025-01-09 15:56 UTC, begelundmuller commented on runtime/metricsview/executor_rewrite_time.go
> +func (e *Executor) GetMinTime(ctx context.Context, colName string) (time.Time, error) {
1. Can drop the `Get`, so just `MinTime`, similar to `Watermark`.
2. All the executors exported functions should be in `runtime/metricsview/executor.go` file – this probably belongs next to the `Watermark` function.
3. Why does this accept a column name? We currently only support one time dimension for metrics views.

2025-01-09 15:56 UTC, begelundmuller commented on runtime/metricsview/executor_rewrite_time.go
> +	rt, err := rilltime.Parse(tr.RillTime)
Can we avoid calling this `rt` – we often use that abbreviation for the `Runtime` object, e.g. `e.rt` in this context is the `Runtime` object. So it's a bit too confusing.

2025-01-09 15:56 UTC, begelundmuller commented on runtime/metricsview/executor_rewrite_time.go
> +	}
This gets called if `tr.Start` or `tr.End` are set – I wouldn't really consider that legacy behavior (which entails we will be deprecating it), it's something we will probably always support

2025-01-09 15:56 UTC, begelundmuller commented on runtime/metricsview/executor_rewrite_time.go
> +	}
`t` is very ambiguous now, probably call it `watermark`

2025-01-09 15:56 UTC, begelundmuller commented on runtime/metricsview/executor_rewrite_time.go
> +		MaxTime:    t,
The watermark is not necessarily `MaxTime` – it may be, but users can override it to something else (e.g. to avoid partial data). 

The design doc says to differentiate between the `earliest`, `latest`, `now` and `watermark` constants: https://www.notion.so/rilldata/Time-range-and-time-range-series-syntax-0be92cca367a425682bb5ea09032b260?pvs=4#131ba33c8f578010b792cac30273e818

2025-01-09 15:56 UTC, begelundmuller commented on runtime/metricsview/executor_rewrite_time.go
> +	}
It feels a bit heavy to run two queries to obtain these values, and if the watermark is not equal to the max time, it will need to run three queries. Since I believe most expressions can be resolved using only one constant, can these be lazily loaded instead of eagerly?

2025-01-09 15:56 UTC, begelundmuller commented on runtime/metricsview/executor_rewrite_time.go
> +	}
Actually it also doesn't handle the error case where e.g. both `Start` and `RillTime` is specified

2025-01-09 15:56 UTC, begelundmuller commented on runtime/metricsview/query.go
> +	RillTime     string    `mapstructure:"rill_time"`
As per the other comment, I would suggest calling this `Expression`

2025-01-09 15:56 UTC, begelundmuller commented on runtime/pkg/metricssql/parser.go
> +	q.executor = ex
Can we avoid needing an `Executor` in this package? It is ideally just supposed to parse the SQL and rewrite it into a `metricsview.Query`, which can accept the raw `rilltime` expression

2025-01-09 15:56 UTC, begelundmuller commented on proto/rill/runtime/v1/queries.proto
> +  rpc MetricsViewResolveTimeRanges(MetricsViewResolveTimeRangesRequest) returns (MetricsViewResolveTimeRangesResponse) {
Can we call this `MetricsViewTimeRanges` – to align with format of the other `MetricsViewXXX` API names

2025-01-09 15:56 UTC, begelundmuller commented on runtime/server/queries_metrics.go
> +		MinTime:         timeRangeQuery.Result.TimeRangeSummary.Min.AsTime(),
It's weird that it resolves `MinTime` separately here, but it resolves the watermark/max time inside the `MetricsViewResolveTimeRanges` implementation.

I would expect a) that it generally resolves these timestamps the same way in most places, b) that it resolves these timestamps at the same place / subject to the same caching.

2025-01-09 15:56 UTC, begelundmuller commented on runtime/pkg/rilltime/rilltime_test.go
> +		{`m : |s|`, "2024-08-09T10:32:00Z", "2024-08-09T10:32:36Z"},
In the (resolved) comments on the doc, we discussed open intervals that end on a time boundary, but I don't think there's a test case for that here. Can you add it? I think an example could be:
```
		{`m : s`, "2024-08-09T10:32:00Z", "2024-08-09T10:32:37Z"},
```

2025-01-09 15:56 UTC, begelundmuller commented on runtime/pkg/rilltime/rilltime.go
> +type RillTime struct {
Instead of `rilltime.RillTime`, consider calling this `rilltime.Expression`

2025-01-09 15:56 UTC, begelundmuller commented on runtime/pkg/rilltime/rilltime.go
> +func (r *RillTime) Resolve(resolverCtx ResolverContext) (time.Time, time.Time, error) {
This is a matter of convention, but we generally use "resolve" for something that makes database queries and "context" for `context.Context` objects. Could we call this `Eval(opts EvalOptions)` or something like that instead?

2025-01-10 05:34 UTC, AdityaHegde commented on proto/rill/runtime/v1/queries.proto
> +  string rill_time = 7;
Will we ever have other expression similar to watermark? If so would it be better to have a separate param for this: `rill_expression` or something?

2025-01-10 05:38 UTC, AdityaHegde commented on runtime/metricsview/executor_rewrite_time.go
> +		MaxTime:    t,
Huh. I thought according Mike we only used `earliest` and `latest`. Lemme add watermark as a separate thing.

2025-01-10 05:44 UTC, AdityaHegde commented on runtime/pkg/metricssql/parser.go
> +	q.executor = ex
This was as per @k-anshul request in his review. @k-anshul any comments?

2025-01-10 05:47 UTC, AdityaHegde commented on runtime/pkg/rilltime/rilltime_test.go
> +		{`m : |s|`, "2024-08-09T10:32:00Z", "2024-08-09T10:32:36Z"},
Wouldnt it be `2024-08-09T10:32:00Z` to `2024-08-09T10:32:36Z`?

2025-01-10 05:51 UTC, AdityaHegde commented on runtime/pkg/rilltime/rilltime.go
> +func (r *RillTime) Resolve(resolverCtx ResolverContext) (time.Time, time.Time, error) {
Changed. So `resolveTimeRange` was called `resolveXX` just because it loaded the watermark from database?

2025-01-10 07:27 UTC, k-anshul commented on runtime/pkg/metricssql/parser.go
> +	q.executor = ex
The parser is already doing some OLAP queries to query watermark so it is not a "typical" parser pkg.
Given we are already making OLAP queries it should be okay to use `Executor` as well since the same function is already part of executor.
Might be wrong but IIRC there was a review comment to use executor's `loadWatermark` instead of defining another `getWatermark` function here : https://github.com/rilldata/rill/blob/fef2386bb980101ebbdd9f7c5ab2b41c3e0d60b4/runtime/pkg/metricssql/time_range_parser.go#L70
I could not use it previously because the implementation is slightly different.

2025-01-10 10:15 UTC, begelundmuller commented on proto/rill/runtime/v1/queries.proto
> +  string rill_time = 7;
I think we are planning on leaning into this time syntax across the product, so I think it's to be expected that `time_range.expression` would use our time range syntax (and of course, the docstring should mention that it uses our own syntax).

If we need to keep separate fields for ISO or SQL syntax (which I hope not), those in turn could be called `iso_expression` and `sql_expression`. But putting a `rill_` prefix IMO does not disambiguate much because the product and package name here are both called Rill already.

2025-01-10 10:18 UTC, begelundmuller commented on runtime/pkg/rilltime/rilltime_test.go
> +		{`m : |s|`, "2024-08-09T10:32:00Z", "2024-08-09T10:32:36Z"},
I believe it should be `...:37Z` – there was a long comment thread about it in the design doc, which seems to have been resolved without updating the main document. Here's one of the relevant comments (to find it, change the comment filter to include resolved comments in Notion):

<img width="328" alt="Screenshot 2025-01-10 at 11 16 44" src="https://github.com/user-attachments/assets/b3b396c2-76cc-4115-b172-afcea12f9468" />

2025-01-10 10:19 UTC, begelundmuller commented on runtime/pkg/rilltime/rilltime.go
> +func (r *RillTime) Resolve(resolverCtx ResolverContext) (time.Time, time.Time, error) {
Yeah

2025-01-10 10:24 UTC, begelundmuller commented on runtime/pkg/metricssql/parser.go
> +	q.executor = ex
I see, in that case I agree that the executor should be used to get the watermark so there's not too much duplication.

I'm not sure if it's possible, but it would still be even better if the SQL time expressions could just be translated to the new time range syntax and then passed into the `metricsview.Query` instead of being resolved inside the parser. However, that's not urgent or a blocker for this PR.

2025-01-13 05:41 UTC, AdityaHegde commented on runtime/compilers/rillv1/parse_explore.go
> +			if ctr.Offset != "" {
Update. Had to move `ValidateISO8601` to achieve this.

2025-01-13 05:46 UTC, AdityaHegde commented on runtime/metricsview/executor_rewrite_time.go
> +	}
Update

2025-01-13 10:36 UTC, AdityaHegde commented on runtime/metricsview/executor_rewrite_time.go
> +func (e *Executor) GetMinTime(ctx context.Context, colName string) (time.Time, error) {
Update for 1 and 2. For 3, we are currently reusing the method for `time_range_start` and `time_range_end` which accepts a column name.

2025-01-14 05:28 UTC, AdityaHegde commented on runtime/server/queries_metrics.go
> +		MinTime:         timeRangeQuery.Result.TimeRangeSummary.Min.AsTime(),
Will raise a follow up to use the metrics_time_range resolver.

2025-01-14 05:30 UTC, AdityaHegde commented on runtime/metricsview/executor_rewrite_time.go
> +	}
I think lazy load will make it a little complex. Will do a follow up that will use metrics_time_range resolver so that these things are cached.

2025-01-14 16:54 UTC, begelundmuller commented
Awaiting integration of this PR before the next review: https://github.com/rilldata/rill/pull/6413#pullrequestreview-2550332129

2025-01-17 16:16 UTC, begelundmuller commented on runtime/queries/metricsview_resolve_time_ranges.go
> +type MetricsViewTimeRanges struct {
This basically just a) calls the timestamps resolver (which may be cached in the resolver cache), b) calls `rilltime`, which doesn't involve heavy operations and should be fast. So can the logic here just be moved directly to the API handler for `MetricsViewTimeRanges`? Since there is no need for separate caching of the result here.

It's also nice not to add new logic to the `runtime/queries` package since it's being deprecated.

2025-01-17 16:29 UTC, begelundmuller requested changes

2025-01-17 16:29 UTC, begelundmuller commented on runtime/pkg/rilltime/rilltime.go
> +			Now: true,
Shouldn't the watermark be the default end if not specified?

2025-01-17 16:29 UTC, begelundmuller commented on runtime/pkg/rilltime/rilltime.go
> +	rt.timeZone = time.UTC
Can we add support for passing in the default time zone? E.g. we have had some requests to use the same time zone as the `refresh:` clause when evaluating and formatting data for alerts and reports.

2025-01-17 16:29 UTC, begelundmuller commented on runtime/pkg/rilltime/rilltime_test.go
> +		{`m : s`, "2024-08-09T10:32:00Z", "2024-08-09T10:32:37Z"},
Shouldn't it be:
```
		{`m : |s|`, "2024-08-09T10:32:00Z", "2024-08-09T10:32:36Z"},
```
like it was before? I.e. `|s|` leads to `:36Z` and `s` leads to `:37Z`.

The idea being that `|s|` indicates that only completed bins should be included – but if `maxTime=...:36Z`, more events may yet appear with `time=...:36Z`. And callers who are good with bins that have potentially partial data should use `m : s`.

2025-01-20 04:12 UTC, AdityaHegde commented on runtime/pkg/rilltime/rilltime_test.go
> +		{`m : s`, "2024-08-09T10:32:00Z", "2024-08-09T10:32:37Z"},
Hmmm. So the idea is that our bins are `ts >= 0 and ts < next 0`? So a data point at the boundary is actually part of next grain. That is why `|s|` will not include it since it is incomplete. We should make sure we explain all these things in our docs, will note it down.

2025-01-20 04:13 UTC, AdityaHegde commented on runtime/pkg/rilltime/rilltime.go
> +			Now: true,
Lemme check with mike today. The docs mention that it should be now. But it probably make sense to do latest/watermark.

2025-01-20 11:16 UTC, begelundmuller commented on runtime/pkg/rilltime/rilltime_test.go
> +		{`m : s`, "2024-08-09T10:32:00Z", "2024-08-09T10:32:37Z"},
Yeah that's the idea!

2025-01-20 16:34 UTC, AdityaHegde commented on runtime/pkg/rilltime/rilltime.go
> +			Now: true,
Got a confirmation from @nishantmonu51 to use watermark.

2025-01-21 16:29 UTC, begelundmuller approved these changes

2025-01-21 16:32 UTC, k-anshul approved these changes

2025-01-21 16:33 UTC, merged