2 phase comparison query
rilldata/rill pull request #6337
Opened 2024-12-30 17:18 UTC by pjain1

Split comparison time range query into two phase -
1. Run a groupby query on base time range
2. Run another query which joins the inline results from first query with groupby comparison query having added filter from base query

- This optimization is only possible when sorting by base column.
- CTE rewrite is disabled by default now as it cause double scan of CTE in Druid, Duckdb and CH. It can be enabled but does not take effect if 2 phase optimization is done. It can be enabled to run queries on very high cardinality (~1M or greater) when sorting by other than base column which may fail in engines like Druid with ResourceLimitException.

2024-12-31 15:33 UTC, pjain1 commented
Another approach is to do two separate topn queries for base and comparison time range and then a 3rd query with results from both queries to calculate measures and return the results, have a working code for this approach as well in a branch. However, this seems more cleaner and does only 2 queries.

2025-01-10 11:39 UTC, begelundmuller requested changes
> > CTE rewrite is disabled by default now as it cause double scan of CTE in Druid, Duckdb and CH. It can be enabled but does not take effect if 2 phase optimization is done. It can be enabled to run queries on very high cardinality (~1M or greater) when sorting by other than base column which may fail in engines like Druid with ResourceLimitException.

Would it make sense to keep it enabled for exports, since we probably shouldn't use the two-phase approach for exports, which may have high cardinality results?

2025-01-10 11:39 UTC, begelundmuller commented on runtime/drivers/registry.go
> +		MetricsTwoPhaseComparisons:        true,
Would it make sense to differentiate between queries with a small limit and (unlimited) queries like exports? Since I guess the two-phase approach will not be suitable for high cardinality results?

If yes, do you think it would be best to keep falling back to the CTE approach for unlimited queries, or should it just fall back to the non-CTE approach?

2025-01-10 11:39 UTC, begelundmuller commented on runtime/metricsview/ast.go
> +	InlineMeasureFields  [][]FieldNode    // Measure fields to select in the inline view, row based representation of the measures. Each index in the outer array represents a row in the inline view.
Based on our sync discussion, would it make sense instead to:
1. Support a field like: `RawSelect *ExprNode // Raw SELECT statement with args. If set, other fields like FromSelect, Where, etc. are ignored.`
2. Populating `DimFields` and `MeasureFields` with the columns returned by the `RawSelect` subquery (instead of having separate `InlineXXX` variants)

(This is just a suggestion, not sure if I have enough context yet to determine if it's the best approach.)

2025-01-10 11:39 UTC, begelundmuller commented on runtime/metricsview/ast.go
> +				}
1. As we discussed, this should ideally be pushed into the dialects. 
2. I'm not sure we can really rely just on the Go types here. It would be best to take into account the DB-level types, to prevent comparison/union issues in joins. This can perhaps be accomplished by leveraging the `drivers.Result.Schema` which is returned when querying the OLAP.
    - There are also people who use non-basic types for dimensions, e.g. a `CODE_STRUCT`. Ideally we handle all these types, but that is probably not feasible initially. Instead, whenever we see a dimension/measure type used that we can't handle, we should probably fail gracefully by skipping the two-phase optimization.
4. Also, did you look into if we can leverage positional args instead of putting literals into the strings (similar to how `ExprNode` works)? I'm not sure if that's a good idea or not, just asking.

2025-01-10 11:39 UTC, begelundmuller commented on runtime/metricsview/ast.go
> +					v = nilExpr
Why can't we use `null` in SQL to represent nils?

2025-01-10 11:39 UTC, begelundmuller commented on runtime/metricsview/ast.go
> +							{Name: dim.(string)},
If `dim` comes from an OLAP query, I don't think you can be sure it's a string. As mentioned above, we support e.g. struct/map dims.

2025-01-10 11:39 UTC, begelundmuller commented on runtime/metricsview/query.go
> +	inlineMeasures   map[any][]any `mapstructure:"-"` // measure -> column values
It somehow feels dirty to add this internal state to the `Query` type (it's widely used many places, but the internal state here applies to a specific internal optimization). Contrast this with the `rewriteQueryDruidExactify`, which despite rewriting the query does not need to add any internal fields. To the extent possible, it would be nice if the two-phase approach could live mainly in the `executor_rewrite_two_phase` file, and only need minimal changes to the generic types in this package. 

Did you consider implementing the optimization by traversing the `AST` type instead of `Query`, similar to how `rewriteApproxComparisons` works?

2025-01-14 06:42 UTC, pjain1 commented on runtime/drivers/registry.go
> +		MetricsTwoPhaseComparisons:        true,
I think it should fall back to non-CTE approach which works faster than CTE in general. However it causes issues with druid dimensions having high cardinality column so for those customer we can enable CTE approach. Best would to be have non-CTE enabled, monitor for ResourceLimitExceeced exception and automatically fall back to CTE approach

2025-01-14 06:43 UTC, pjain1 commented on runtime/metricsview/ast.go
> +					v = nilExpr
outdated and removed, however we are using NULL while writing sql when we encounter this exception

2025-01-14 06:43 UTC, pjain1 commented on runtime/metricsview/query.go
> +	inlineMeasures   map[any][]any `mapstructure:"-"` // measure -> column values
removed

2025-01-14 13:40 UTC, pjain1 commented on runtime/metricsview/ast.go
> +	InlineMeasureFields  [][]FieldNode    // Measure fields to select in the inline view, row based representation of the measures. Each index in the outer array represents a row in the inline view.
I have not tried `ExprNode` approach, just was sql as of now. Will try it out

2025-01-14 13:41 UTC, pjain1 commented on runtime/metricsview/ast.go
> +							{Name: dim.(string)},
using query dim name now directly from the query

2025-01-14 13:43 UTC, pjain1 commented
> Would it make sense to keep it enabled for exports, since we probably shouldn't use the two-phase approach for exports, which may have high cardinality results?

For exports of high cardinality columns even with CTE approach we don't add limit to the CTE query and that fails with Resource Limit Exceeded exception. I think we need another config to limit base query as well ? Thoughts ?

2025-01-14 16:27 UTC, begelundmuller commented
FYI the tests are still failing

2025-01-15 12:04 UTC, begelundmuller requested changes

2025-01-15 12:04 UTC, begelundmuller commented on runtime/drivers/olap.go
> +		return true, fmt.Sprintf("CAST('%s' AS TIMESTAMP)", t.Format(time.RFC3339))
Should it use `time.RFC3339Nano`? The databases usually have at least millisecond precision, but `RFC3339` only has second precision IIRC

2025-01-15 12:04 UTC, begelundmuller commented on runtime/drivers/olap.go
> +		return true, fmt.Sprintf("'%v'", val), nil
Is there a reason you didn't go with putting `?` and returning an array of positional args to bind to the query?

2025-01-15 20:11 UTC, pjain1 commented on runtime/metricsview/executor_rewrite_two_phase_comparisons.go
> +			// only supported sorting on base value and dims TODO extend for comparison value
not urgent as UI does not seem to be sorting by comparison value anywhere

2025-01-15 20:12 UTC, pjain1 commented on runtime/drivers/olap.go
> +		return true, fmt.Sprintf("'%v'", val), nil
changed to use positional args for CH and duckdb, druid does not support positional args for inline queries

2025-01-16 11:01 UTC, begelundmuller commented on runtime/metricsview/executor_rewrite_two_phase_comparisons.go
> +			// only supported sorting on base value and dims TODO extend for comparison value
What about this? But we can handle it in a follow up if it's not easy

<img width="1569" alt="Screenshot 2025-01-16 at 12 00 47" src="https://github.com/user-attachments/assets/c3a0e745-cd71-489b-813f-35802c0e64f0" />

2025-01-16 11:04 UTC, pjain1 commented on runtime/metricsview/executor_rewrite_two_phase_comparisons.go
> +			// only supported sorting on base value and dims TODO extend for comparison value
this is sorting by delta not comparison

2025-01-16 11:07 UTC, begelundmuller approved these changes

2025-01-16 12:58 UTC, merged